on: ["workflow_dispatch"]
name: Sync
jobs:
  sync:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: GitHub user
      run: |
        # https://api.github.com/users/github-actions[bot]
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Sync
      run: |
        make # pull fetch patch gen mod test
        git commit -m 'sync: fetch ${{ steps.date.outputs.date }} spec and apply patches' *.json
        git add v1
        git commit -m 'sync: generate client with ${{ steps.date.outputs.date }} spec' v1
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: sync/gh
        branch-suffix: timestamp
        title: API Sync by GitHub Action (${{ steps.date.outputs.date }})
        body: |
          This API Sync PR was automated through [GitHub Actions workflow_displatch](https://github.com/t0mk/gometal/actions?query=event%3Aworkflow_dispatch)
          on ${{ steps.date.outputs.date }}.

          * latest Swagger is fetched
          * patches have been applied
          * generated client has been updated
        delete-branch: true
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
